#!/bin/bash
set -eu
replace_ref="$3"
DOKANY_GIT_URL=$2

rm -rf $1-connected
git clone $1 $1-connected
cd $1-connected
git remote add dokany-git "$DOKANY_GIT_URL"
git fetch dokany-git
git checkout $replace_ref
git symbolic-ref HEAD refs/heads/master
git commit -F ../connecting-commit.commitmsg
git replace $replace_ref master
git reset --hard dokany-git/master

echo Done
